name: Cat
author: Arne Tarara <arne@green-coding.berlin>
version: 1
description: Cat

services:
  test-container:
    build:
       context: ./subdir
       dockerfile: ./subdir2/Dockerfile
    image: volume_bind_mount_rel_to_context
    container_name: test-container
    volumes:
      - ./subdir/testfile:/tmp/testfile-correctly-mounted
      - ./subdir/subdir2/testfile2:/tmp/testfile2-correctly-mounted
      - ./subdir/subdir2/subdir3/testfile3:/tmp/testfile3-correctly-mounted
    cmd: sh

flow:
  - name: Cat
    container: test-container
    commands:
      - type: console
        command: cat /tmp/testfile-correctly-mounted


