name: Cat Subdir
author: Arne Tarara <arne@green-coding.berlin>
version: 1
description: Cat Subdir

services:
  test-container:
    build:
       context: ./subdir2
       dockerfile: Dockerfile
    image: volume_bind_mount_rel_to_context
    container_name: test-container
    volumes:
      - ./subdir2/testfile2:/tmp/testfile2-correctly-mounted
      - ./subdir2/subdir3/testfile3:/tmp/testfile3-correctly-mounted
    cmd: sh

flow:
  - name: Cat Subdir
    container: test-container
    commands:
      - type: console
        command: cat /tmp/testfile3-correctly-mounted


